export enum ipcEventEnum {
    openNewWindow = 'openNewWindow',
    backUp = 'backUp',
    updateData = 'updateData',
    setFolderBackup = 'setFolderBackup',
    getAppVersion = 'getAppVersion',
    deleteFilesBackUp = 'deleteFilesBackUp',
    restoreFilesBackUp = 'restoreFilesBackUp',
    getFilesBackUp = 'getFilesBackUp',
    getDBFolder = 'getDBFolder',
    getEnv = 'getEnv',
    postErrorLog = 'postErrorLog',
    quit = 'quit',
    exportImages = 'exportImages',
    restartApp = 'restartApp',
    fullWindow = 'fullWindow',
    refreshFilesBackUp = 'refreshFilesBackUp',
    checkUpdate = 'checkUpdate',
    checkNewVersion = 'checkNewVersion',
    closeWindowOutParent = 'closeWindowOutParent',
}
